version: '3.8'
services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-local-new
    environment:
      MYSQL_ROOT_PASSWORD: skyknight31
      MYSQL_DATABASE: gestionplusdb
      MYSQL_USER: root
      MYSQL_PASSWORD: skyknight31
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

networks:
  laravel:


volumes:
  dbdata:
